# Generated by Django 4.2.1 on 2023-08-12 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_product_created_at_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="producator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.producer",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="contacts",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="contacts",
            name="phone",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
