services:
  exotic-api:
    container_name: exotic-api
    build:
      context: ./
      dockerfile: deployment/docker/Dockerfile
    image: exotic-api
    volumes:
      - ./db.sqlite3:/usr/app/db.sqlite3
      - ./static:/usr/app/static:ro
      - ./media:/usr/app/media:ro
    expose:
      - "8000"

  exotic-nginx:
    image: nginx:1.27.3-alpine
    container_name: exotic-nginx
    volumes:
      - ./deployment/docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/app/static:ro
      - ./media:/usr/app/media:ro
    ports:
      - "8090:80"
    depends_on:
      - exotic-api