apiVersion: v1
kind: ConfigMap
metadata:
  name: exotic-nginx-conf
data:
  default.conf: |
    server {
      include /etc/nginx/mime.types;
      default_type application/octet-stream;

      listen 80;
      server_name localhost;
      server_tokens off;
      add_header X-Content-Type-Options "nosniff" always;

      location /static/ {
          alias /usr/app/static/;
          access_log off;
          expires 30d;
          add_header Cache-Control "public";
          types {
              text/css css;
              application/javascript js;
              font/woff2 woff2;
          }
          add_header Content-Type $content_type;
          types {
              image/jpeg  jpg jpeg;
              image/png   png;
              text/css    css;
              application/javascript js;
          }

          add_header Content-Type $content_type;
          add_header X-Content-Type-Options "nosniff" always;
      }

      location /media/ {
          alias /usr/app/media/;
          access_log off;
          expires 30d;
          add_header Cache-Control "public";
          types {
              image/jpeg  jpg jpeg;
              image/png   png;
          }

          add_header Content-Type $content_type;
          add_header X-Content-Type-Options "nosniff" always;
      }

      location / {
          proxy_pass http://exotic-api-service:8000;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_set_header X-Forwarded-Host $host;

          proxy_hide_header X-Powered-By;
          proxy_hide_header Server;

          proxy_connect_timeout 5s;
          proxy_read_timeout 60s;
          proxy_send_timeout 60s;
      }

      location ~* \.(py|pyc|pyo|db|sqlite3|log|git|env|cfg|ini)$ {
          deny all;
      }
    }
