apiVersion: apps/v1
kind: Deployment
metadata:
  name: exotic-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: exotic-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: exotic-api
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: exotic-api
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
          image: refjs/utmacdjango
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: exotic-api-config

          livenessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /api/health
              port: 8000
            initialDelaySeconds: 15  # mai generos
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          startupProbe:
            httpGet:
              path: /api/health
              port: 8000
            failureThreshold: 30
            periodSeconds: 5



          volumeMounts:
            - name: static-volume
              mountPath: /usr/app/static
            - name: media-volume
              mountPath: /usr/app/media
      volumes:
        - name: static-volume
          persistentVolumeClaim:
            claimName: pvc-static
        - name: media-volume
          persistentVolumeClaim:
            claimName: pvc-media
---
apiVersion: v1
kind: Service
metadata:
  name: exotic-api-service
spec:
  selector:
    app: exotic-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
